### ISSUE TITLE
パッケージング時のエラー

### ISSUE THREAD

**Issue by dsuz** [dsuz/petitcon21#4]

**Comment by dsuz** [comment]
C++ でステージシーケンスを作り始めたらビルドエラーが出るようになった。エラー内容は以下の通り。

Output Log
```
UATHelper: Packaging (Windows): Took 25.39s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\vasal\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+Epic+Games+UE_5.3\UBT-petitcon21-Win64-Shipping_2.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 30s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
LogAudioDerivedData: Display: Building compressed audio format BINKA hash BINKA_SCVER_5028_R4DV_false_SR0_48000.000000_SR1_32000.000000_SR2_24000.000000_SR3_12000.000000_SR4_8000.000000_QMOD_1.000000_CQLT_-1_ASTH_0.000000_INLC_false_CSZE_65536_LCF_false_ZCS_0_MCSO_0_END wave CompileFailed...
PackagingResults: Error: Unknown Error
LogAudio: Display: Chunk sizes for SoundWave /Engine/EditorSounds/Notifications/CompileFailed.CompileFailed: Chunk0=28 bytes, Chunk1-N=256k
LogDerivedDataCache: C:/Users/vasal/AppData/Local/UnrealEngine/Common/DerivedDataCache: Maintenance finished in +00:00:32.282 and deleted 0 files with total size 0 MiB and 0 empty folders. Scanned 17115 files in 19220 folders with total size 2377 MiB.
```

UBT-petitcon21-Win64-Shipping_2.txt
```
------ Building 13 action(s) started ------
[1/13] Resource Default.rc2
[2/13] Compile [x64] SharedPCH.Engine.Cpp20.InclOrderUnreal5_0.cpp
[3/13] Compile [x64] StageSequenceData.cpp
E:\Documents\Unreal Projects\petitcon21\Source\petitcon21\Private\StageSequenceData.cpp(2): fatal error C1083: Cannot open include file: 'IPropertyTable.h': No such file or directory
[4/13] Compile [x64] StageManagerBase.cpp
E:\Documents\Unreal Projects\petitcon21\Source\petitcon21\Private\StageManagerBase.cpp(2): fatal error C1083: Cannot open include file: 'Filters/SBasicFilterBar.h': No such file or directory
[5/13] Compile [x64] petitcon21.init.gen.cpp
[6/13] Compile [x64] EGameState.gen.cpp
[7/13] Compile [x64] StageManagerBase.gen.cpp
[8/13] Compile [x64] petitcon21.cpp
[9/13] Compile [x64] StageSequenceData.gen.cpp
[10/13] Compile [x64] GameManagerCpp.gen.cpp
[11/13] Compile [x64] GameManagerCpp.cpp
Total time in Parallel executor: 17.86 seconds
Total execution time: 25.25 seconds
CompilationResultException: Error: OtherCompilationError
   at UnrealBuildTool.ActionGraph.ExecuteActionsAsync(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute, List`1 TargetDescriptors, ILogger Logger, IActionArtifactCache actionArtifactCache) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 417
   at UnrealBuildTool.BuildMode.BuildAsync(TargetMakefile[] Makefiles, List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 801
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 411
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
WriteFileIfChanged() wrote 53 changed files of 53 requested writes.
```

**Comment by dsuz** [comment]
問題はここ

```
[3/13] Compile [x64] StageSequenceData.cpp
E:\Documents\Unreal Projects\petitcon21\Source\petitcon21\Private\StageSequenceData.cpp(2): fatal error C1083: Cannot open include file: 'IPropertyTable.h': No such file or directory
[4/13] Compile [x64] StageManagerBase.cpp
E:\Documents\Unreal Projects\petitcon21\Source\petitcon21\Private\StageManagerBase.cpp(2): fatal error C1083: Cannot open include file: 'Filters/SBasicFilterBar.h': No such file or directory
```

ソースファイルを見てみると、エラーになっているヘッダーは使っていなかった。include を削除してビルド・パッケージングは問題なくできるようになった。
